///////////////////////////////////////////////////////////
//  FlowerPlotIteration.cs
//  Implementation of the Class FlowerPlotIteration
//  Generated by Enterprise Architect
//  Created on:      15-Jul-2018 8:18:01 PM
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using gardenpkg;
namespace gardenpkg {
	public class FlowerPlotIteration {

		private float area;
		private int harvestDate;
		private float moisturePerc;
		private int plantingDate;
		private int stage;
		public gardenpkg.Flower m_Flower;
		public gardenpkg.SoilType m_SoilType;

		public FlowerPlotIteration(){

		}

		~FlowerPlotIteration(){

		}

	}//end FlowerPlotIteration

}//end namespace gardenpkg