///////////////////////////////////////////////////////////
//  Flower.cs
//  Implementation of the Class Flower
//  Generated by Enterprise Architect
//  Created on:      15-Jul-2018 8:18:01 PM
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace gardenpkg {
	public class Flower {

		private string name;

		public Flower(){

		}

		~Flower(){

		}

	}//end Flower

}//end namespace gardenpkg