///////////////////////////////////////////////////////////
//  SoilType.cs
//  Implementation of the Class SoilType
//  Generated by Enterprise Architect
//  Created on:      15-Jul-2018 8:18:01 PM
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace gardenpkg {
	public class SoilType {

		private int clayPercent;
		private int sandPercent;
		private int siltPercent;

		public SoilType(){

		}

		~SoilType(){

		}

	}//end SoilType

}//end namespace gardenpkg